language: python
sudo: false
python:
- 3.6
env:
  global:
  - CONDA_DEPS="numpy scipy matplotlib lmfit asteval natsort pytest pytest-cov"
  - PACKAGENAME="peakfit"
before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda create -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- conda install -c conda-forge $CONDA_DEPS
- pip install nmrglue
install:
- python setup.py install
script:
- pytest -v --color=yes --cov=$PACKAGENAME tests
after_success:
- conda install -c conda-forge codecov
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: gbouvignies
  password:
    secure: CA0gk1bimkEHtObKBEvFzEzn9h3lc2evfHd2K0CRv4wW8o5ZFxpiMkyIWMOuR43VbI5ujZxEYqFJS2ZiPIs8lIrKtNfsYYlV/W1cU5KzSwYZrWXqseCuKZ+HTqIqN/MfFe54OsMztGOVkcdbH0Y/850UKofVmws6FKh7T7JBVP07ADP8qCzJjm3kwgK4J8oQCLrdg6bXJdOO92BThimLVsv6x3huUTrmXyP//UXRB6fTsRsW7pN9CSLzzVxh1qOfWCxsBZ631olFLNVZB+uawXZ3s5+qucapxJiGXgzBJCJ3HiMZ5py7ASVbmsrZjNVZinbvwv8KUXf5L+CNU7+ksyXImQMSpbv7PGmueUpcxWtZ5Y3x0Lrqb2WfUHXHXydzV/3m53uzQnLD5pqjeFE9jrSKCPb2AS4clp9biiKf3Vd6ppB1aaeLDDt1j/Kl7DvuPxltCvov8eMBe/bkQMIW4zF7p3gI7fuv6X9wh79KcggNBpWxy946xu3Urb+oPbca2eo0XwRcFKcXpkrWULa7lazg9vvUUAjt0RVVMfICr9abVSQ/SiRYQPzy2UeIckPWReRv8eX/eG3o/OosoJXN8eTdjzMfngDU/mBhsJYtzFGFWdLhX98ZnLaguvVfgHO9YSMKb0HBXIEFAQdAzPwB5O+zss7NkPg/hJ/OjgID2Vo=
  on:
    tags: true
    repo: gbouvignies/PeakFit
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
