"""Simplified lineshapes package for NMR peak fitting.

All shapes treated equally with uniform J-coupling support.
Single Numba kernel handles all shape types.
"""

from peakfit.lineshapes import functions
from peakfit.lineshapes.catalog import ShapeComputationCatalog, batch_evaluate_with_catalog
from peakfit.lineshapes.functions import (
    KERNEL_REGISTRY,
    compute_all_gaussian_shapes,
    compute_all_lorentzian_shapes,
    compute_all_no_apod_shapes,
    compute_all_pvoigt_shapes,
    compute_all_sp1_shapes,
    compute_all_sp2_shapes,
    compute_ata_symmetric,
    compute_atb,
    evaluate_apod_shape,
    evaluate_apod_shape_no_apod,
    evaluate_apod_shape_sp1,
    evaluate_apod_shape_sp2,
    gaussian,
    lorentzian,
    no_apod,
    pvoigt,
    sp1,
    sp2,
    warm_numba_cache,
)
from peakfit.lineshapes.models import (
    SHAPES,
    SP1,
    SP2,
    ApodShape,
    BaseShape,
    Gaussian,
    Lorentzian,
    NoApod,
    PeakShape,
    PseudoVoigt,
    Shape,
    get_shape,
    list_shapes,
    register_shape,
)

__all__ = [
    "KERNEL_REGISTRY",
    "SHAPES",
    "SP1",
    "SP2",
    "ApodShape",
    "BaseShape",
    "Gaussian",
    "Lorentzian",
    "NoApod",
    "PeakShape",
    "PseudoVoigt",
    "Shape",
    "ShapeComputationCatalog",
    "batch_evaluate_with_catalog",
    "compute_all_gaussian_shapes",
    "compute_all_lorentzian_shapes",
    "compute_all_no_apod_shapes",
    "compute_all_pvoigt_shapes",
    "compute_all_sp1_shapes",
    "compute_all_sp2_shapes",
    "compute_ata_symmetric",
    "compute_atb",
    "evaluate_apod_shape",
    "evaluate_apod_shape_no_apod",
    "evaluate_apod_shape_sp1",
    "evaluate_apod_shape_sp2",
    "functions",
    "gaussian",
    "get_shape",
    "list_shapes",
    "lorentzian",
    "no_apod",
    "pvoigt",
    "register_shape",
    "sp1",
    "sp2",
    "warm_numba_cache",
]
