"""Centralized constants and default parameters for PeakFit."""

# Least-Squares Optimization Defaults
LEAST_SQUARES_FTOL = 1e-7
LEAST_SQUARES_XTOL = 1e-7
LEAST_SQUARES_MAX_NFEV = 1000

# Basin-Hopping Optimization Defaults
BASIN_HOPPING_NITER = 100
BASIN_HOPPING_TEMPERATURE = 1.0
BASIN_HOPPING_STEPSIZE = 0.5
BASIN_HOPPING_LOCAL_MAXITER = 1000

# Differential Evolution Defaults
DIFF_EVOLUTION_MAXITER = 1000
DIFF_EVOLUTION_POPSIZE = 15
DIFF_EVOLUTION_MUTATION = (0.5, 1.0)
DIFF_EVOLUTION_RECOMBINATION = 0.7

# Convergence Criteria
CONVERGENCE_CHI2_THRESHOLD = 1e-4
MAX_REFINEMENT_ITERATIONS = 3

# Uncertainty Estimation
PROFILE_LIKELIHOOD_NPOINTS = 20
PROFILE_LIKELIHOOD_DELTA_CHI2 = 3.84
MCMC_N_WALKERS = 32
MCMC_N_STEPS = 1000
MCMC_BURN_IN = 200

# Progress Display
PROGRESS_UPDATE_INTERVAL = 1

# Benchmarking
BENCHMARK_MAX_NFEV = 500
