#!/bin/bash
# Example 2: Advanced Fitting with CEST Analysis
# This script demonstrates fitting a pseudo-3D CEST NMR spectrum

set -e  # Exit on error

echo "=========================================="
echo "PeakFit Example 2: CEST Analysis"
echo "=========================================="
echo

# Check if PeakFit is installed
if ! command -v peakfit &> /dev/null; then
    echo "Error: peakfit command not found"
    echo "Please install PeakFit first:"
    echo "  uv sync --extra dev    # Recommended development install"
    echo "  OR from repository: pip install -e ."
    exit 1
fi

# Check data files exist
if [ ! -f "data/pseudo3d.ft2" ]; then
    echo "Error: Data files not found"
    echo "Make sure you're running this script from the 02-advanced-fitting/ directory"
    exit 1
fi

# Clean previous results
if [ -d "Fits" ]; then
    echo "Cleaning previous results..."
    rm -rf Fits
fi

echo "Step 1: Validating inputs..."
echo
peakfit validate data/pseudo3d.ft2 data/pseudo3d.list

echo
echo "Step 2: Running CEST fit..."
echo "  This will fit 166 peaks across 131 planes (~2-3 minutes)"
echo
peakfit fit \
    data/pseudo3d.ft2 \
    data/pseudo3d.list \
    --z-values data/b1_offsets.txt \
    --output Fits/

echo
echo "=========================================="
echo "Fitting complete!"
echo "=========================================="
echo
echo "Results saved to: Fits/"
echo
echo "  Main outputs:"
echo "    - Fits/fit_results.json  : Complete results (machine-readable)"
echo "    - Fits/parameters.csv    : Parameter table (for Excel/pandas)"
echo "    - Fits/report.md         : Human-readable summary"
echo "    - Fits/peakfit.log       : Detailed log file"
echo
echo "  Note: Legacy .out files are no longer generated by default."
echo "  Use --legacy flag if you need them: peakfit fit ... --legacy"
echo
echo "Next steps:"
echo "  • View JSON results: cat Fits/fit_results.json | head -50"
echo "  • Load in Python: pd.read_csv('Fits/parameters.csv')"
echo "  • View log: less Fits/peakfit.log"
echo
